/** Generated by scripts/prepare-carnet-art.mjs. Native-size original illustrations. */
export const CARNET_ART: Readonly<Record<string, { src: string; width: number; height: number }>> = {
  "projets": {
    "src": "/assets/pixel/carnet-1.1/bandeaux/projets.webp",
    "width": 2172,
    "height": 724
  },
  "commandes": {
    "src": "/assets/pixel/carnet-1.1/bandeaux/commandes.webp",
    "width": 2172,
    "height": 724
  },
  "foires": {
    "src": "/assets/pixel/carnet-1.1/bandeaux/foires.webp",
    "width": 2172,
    "height": 724
  },
  "vallee": {
    "src": "/assets/pixel/carnet-1.1/bandeaux/vallee.webp",
    "width": 2172,
    "height": 724
  },
  "maitrise": {
    "src": "/assets/pixel/carnet-1.1/bandeaux/maitrise.webp",
    "width": 2172,
    "height": 724
  },
  "objectifs": {
    "src": "/assets/pixel/carnet-1.1/bandeaux/objectifs.webp",
    "width": 2172,
    "height": 724
  },
  "ameliorer": {
    "src": "/assets/pixel/carnet-1.1/bandeaux/ameliorer.webp",
    "width": 2172,
    "height": 724
  },
  "savoir-faire-culture": {
    "src": "/assets/pixel/carnet-1.1/bandeaux/savoir-faire-culture.webp",
    "width": 2172,
    "height": 724
  },
  "savoir-faire-cuisine": {
    "src": "/assets/pixel/carnet-1.1/bandeaux/savoir-faire-cuisine.webp",
    "width": 2172,
    "height": 724
  },
  "savoir-faire-commerce": {
    "src": "/assets/pixel/carnet-1.1/bandeaux/savoir-faire-commerce.webp",
    "width": 2172,
    "height": 724
  },
  "atelier": {
    "src": "/assets/pixel/carnet-1.1/bandeaux/atelier.webp",
    "width": 2172,
    "height": 724
  },
  "savoir-faire": {
    "src": "/assets/pixel/carnet-1.1/bandeaux/savoir-faire-culture.webp",
    "width": 2172,
    "height": 724
  }
};
