export const CROPS = [
  {
    id: 'radis',
    name: 'Radis',
    icon: '🌱',
    fruit: '🔴',
    level: 1,
    time: 30,
    cost: 2,
    price: 7,
    xp: 2,
    mastery: 1,
    tag: 'Active et rapide · faible valeur par geste',
  },
  {
    id: 'carotte',
    name: 'Carotte',
    icon: '🥕',
    fruit: '🥕',
    level: 2,
    time: 60,
    cost: 4,
    price: 13,
    xp: 5,
    mastery: 2,
    tag: 'Idéale pour les commandes courtes',
  },
  {
    id: 'ble',
    name: 'Blé',
    icon: '🌾',
    fruit: '🌾',
    level: 5,
    time: 120,
    cost: 5,
    price: 17,
    xp: 12,
    mastery: 3,
    tag: 'Indispensable au pain et aux poules',
  },
  {
    id: 'salade',
    name: 'Laitue',
    icon: '🥬',
    fruit: '🥬',
    level: 3,
    time: 90,
    cost: 5,
    price: 12,
    xp: 7,
    mastery: 2,
    tag: 'Fraîcheur des commandes courtes',
  },
  {
    id: 'tomate',
    name: 'Tomate',
    icon: '🍅',
    fruit: '🍅',
    level: 8,
    time: 180,
    cost: 9,
    price: 27,
    xp: 19,
    mastery: 4,
    tag: 'La reine de la transformation',
  },
  {
    id: 'fraise',
    name: 'Fraise',
    icon: '🍓',
    fruit: '🍓',
    level: 10,
    time: 300,
    cost: 12,
    price: 36,
    xp: 28,
    mastery: 5,
    tag: 'La douceur des confitures',
  },
  {
    id: 'mais',
    name: 'Maïs',
    icon: '🌽',
    fruit: '🌽',
    level: 12,
    time: 600,
    cost: 15,
    price: 52,
    xp: 46,
    mastery: 7,
    tag: 'Production intermédiaire rentable',
  },
  {
    id: 'aubergine',
    name: 'Aubergine',
    icon: '🍆',
    fruit: '🍆',
    level: 15,
    time: 900,
    cost: 20,
    price: 72,
    xp: 62,
    mastery: 8,
    tag: 'Rentable et utile à la ratatouille',
  },
  {
    id: 'myrtille',
    name: 'Myrtille',
    icon: '🫐',
    fruit: '🫐',
    level: 17,
    time: 1200,
    cost: 28,
    price: 105,
    xp: 86,
    mastery: 10,
    tag: 'Parfaite pendant une longue absence',
  },
  {
    id: 'citrouille',
    name: 'Citrouille',
    icon: '🎃',
    fruit: '🎃',
    level: 19,
    time: 1800,
    cost: 35,
    price: 145,
    xp: 115,
    mastery: 12,
    tag: 'À laisser grandir tranquillement',
  },
  {
    id: 'raisin',
    name: 'Raisin',
    icon: '🍇',
    fruit: '🍇',
    level: 21,
    time: 3600,
    cost: 45,
    price: 220,
    xp: 175,
    mastery: 16,
    tag: 'Grande valeur et qualités généreuses',
  },
  {
    id: 'melon',
    name: 'Melon',
    icon: '🍈',
    fruit: '🍈',
    level: 23,
    time: 7200,
    cost: 65,
    price: 360,
    xp: 280,
    mastery: 22,
    tag: 'Récolte rare et prestigieuse',
  },
];
